# Local/Dev
version: '2'
services:
    web:
        image: frojd/wagtial-alt-generator-web
        build: .
        volumes:
            - ./:/app
        ports:
            - "8086:8000"
        depends_on:
            - db
        links:
            - db
        environment:
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - DJANGO_SETTINGS_MODULE=examplesite.settings.dev
        env_file: web.env
    db:
        image: postgres
        restart: always
        ports:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
